// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `json:"username"`
	Gender   int64  `json:"gender"`
}

type FindUserReq struct {
	UserId string `form:"userId"`
}

type FindUserRes struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   string `json:"gender"`
}

type CommonRes struct {
	IRet int64  `json:"iRet"`
	SMsg string `json:"sMsg"`
}
